allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  core-js: false
  core-js-pure: false
  esbuild: set this to true or false
  lefthook: false
  msgpackr-extract: set this to true or false
  prisma: false
  sharp: false
  unrs-resolver: false
  workerd: set this to true or false
